name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
# ?  add needed inputs
inputs:
  bucket:
    description: 'The S3 Bucket name'
    required: true
  bucket-region:
    description: 'The region of S3 Bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files'
    required: true
#| we want to show the generated url by AWS
outputs:
  website-url:
    description: 'The Url of teh deployed website'
    #* here we don't set the value instead we set it in the main.js

runs:
  using: 'node20'
  main: 'main.js'
# which should simply be the path to the folder that contains the files that should be uploaded to that bucket,So the website-files in our case.
# after defining inputs now we have to use then into the main.js
