name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3'
runs:
  using: 'node20' #| identifier to specify this is js custom action :more info below link
  main: 'main.js' # *  GitHub Actions will do then is it will execute that main.js file and therefore execute all the logic that might be in that file whenever this custom action is used in a Workflow step.
  # pre:
  #post: we cans et these props ex clean before or after
# * https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions
