name: 'Get & Cache Dependencies'
description: 'get the dependencies (via npm) and cache them'
runs:
  using: 'composite' #| we should set this as composite , it's fixed and steady
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
# * in custom actions we dont have and use on!
# * https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
