name: 'Get & Cache Dependencies'
description: 'get the dependencies (via npm) and cache them'
inputs: #* define inputs
  caching: #* could be anything , the name of input
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
# abc :          we can add inputs as many
# description :

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true' #| check the input is true or false
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
    - name: Log of cache Status
      shell: bash
      run: echo "Caching is" ${{ inputs.caching }}
