name: 'Get & Cache Dependencies'
description: 'get the dependencies (via npm) and cache them'
inputs:
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'

outputs: #* define output
  used-cache: # * could be anything , the name of output
    description: 'Whether Cached was used.'
    value: ${{ steps.install.outputs.cachingval }}

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install #| we need id for output
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cachingval=${{ inputs.caching }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Log of cache Status
      shell: bash
      run: echo "Caching is ${{ inputs.caching }}"
